language: java

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
  - master
  - develop

after_success:
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  - bash <(curl -s https://codecov.io/bash)