= Cheatsheets

[[CounterEmitterProcessorOptions]]
== CounterEmitterProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the counter.
 <p>
 The value must be a positive integer.
 <p>
 The counter will emit a signal every <code>interval</code> event received.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[signal]]`signal`|`link:enums.html#Signal[Signal]`|
+++
The signal to emit every interval.
 <p>
 Can be one of <code>FLUSH</code> or <code>TERMINATE</code>
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[DataExtractorProcessorOptions]]
== DataExtractorProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[extract]]`extract`|`Json object`|
+++
The list of fields to extract from input json.
 <p>
 If one of the fields is not found in the input object, the field is ignored.
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[ExchangeOptions]]
== ExchangeOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[controlChannel]]`controlChannel`|`String`|
+++
The control channel to emit/receive signals.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The channel cannot be configured</b>
+++
|[[from]]`from`|`String`|
+++
The address the deployed object will receive items from.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The address cannot be configured</b>
+++
|[[to]]`to`|`Array of String`|
+++
The addresses the deployed object will send results to.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The address cannot be configured</b>
+++
|===

[[FileSinkOptions]]
== FileSinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchSize]]`batchSize`|`Number (Integer)`|
+++
The batch size of the link.
 <p>
 It must be a positive link.
 <p>
 It defaults to <code>10</code>
+++
|[[file]]`file`|`String`|
+++
The file name without extension.
 <p>
 Path and file will be tested on startup to detect whether the link can write.
 <p>
 Defaults to <code>output</code>
+++
|[[format]]`format`|`link:enums.html#Format[Format]`|
+++
The format output of the link.
 <p>
 <code>JSON</code> and <code>YAML</code> are supported.
+++
|[[mode]]`mode`|`link:enums.html#Mode[Mode]`|
+++
The mode of the link
+++
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[path]]`path`|`String`|
+++
The path to store the output.
 <p>
 Path and file will be tested on startup to detect whether the link can write.
 <p>
 Defaults to <code>/tmp</code>
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[FlushableSinkOptions]]
== FlushableSinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchSize]]`batchSize`|`Number (Integer)`|
+++
The batch size of the link.
 <p>
 It must be a positive link.
 <p>
 It defaults to <code>10</code>
+++
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[LogProcessorOptions]]
== LogProcessorOptions

++++
 Log Processor options.
 <p>
 They extend directly base link and provide
 the ability to set the acceptable level to log incoming messages.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[level]]`level`|`link:enums.html#Level[Level]`|
+++
The log  to write the incoming items.
 <p>
 Defaults to <code>DEBUG</code>.
 <p>
 One of:
 <ul>
 <li><code>TRACE</code></li>
 <li><code>DEBUG</code></li>
 <li><code>INFO</code></li>
 <li><code>WARN</code></li>
 <li><code>ERROR</code></li>
 </ul>
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[ObjectToArrayProcessorOptions]]
== ObjectToArrayProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[fields]]`fields`|`Json array`|
+++
The list of fields to transform as an array / list.
 <p>
 If one of the fields is not found in the input object, the field is created with an empty array.
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[PipelineOptions]]
== PipelineOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[deployChannel]]`deployChannel`|`String`|-
|[[name]]`name`|`String`|-
|[[processors]]`processors`|`Json array`|-
|[[pump]]`pump`|`Json object`|-
|[[sink]]`sink`|`Json object`|-
|===

[[ProcessorOptions]]
== ProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[PumpOptions]]
== PumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|===

[[SinkOptions]]
== SinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[TimerEmitterProcessorOptions]]
== TimerEmitterProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the pump.
 <p>
 The value must be a positive integer.
 <p>
 The pump will emit a message every tick containing the
 current counter and timestamp.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[signal]]`signal`|`link:enums.html#Signal[Signal]`|
+++
The signal to emit every interval.
 <p>
 Can be one of <code>FLUSH</code> or <code>TERMINATE</code>
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|[[unit]]`unit`|`link:enums.html#TimeUnit[TimeUnit]`|
+++
The time unit of the pump.
 <p>
 The value is one of
+++
|===

[[TimerPumpOptions]]
== TimerPumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[data]]`data`|`Json object`|
+++
The custom data to add with the tick
 <p>
 It can be any arbitrary json/yaml data.
 <p>
 No additional data is sent when it is null or empty
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the pump.
 <p>
 The value must be a positive integer.
 <p>
 The pump will emit a message every tick containing the
 current counter and timestamp.
+++
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|[[unit]]`unit`|`link:enums.html#TimeUnit[TimeUnit]`|
+++
The time unit of the pump.
 <p>
 The value is one of
+++
|===

