= Cheatsheets

[[CounterEmitterProcessorOptions]]
== CounterEmitterProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[delayTerminate]]`delayTerminate`|`Number (Long)`|
+++
The delay before sending <code>TERMINATE</code> signal.
 <p>
 A <code>FLUSH</code> signal is always emitted before sending
 <code>TERMINATE</code> thus setting delay between both emissions
 can help the pipeline finish his job properly, especially when accumulating data.
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the counter.
 <p>
 The value must be a positive integer.
 <p>
 The counter will emit a signal every <code>interval</code> event received.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[signal]]`signal`|`link:enums.html#Signal[Signal]`|
+++
The signal to emit every interval.
 <p>
 Can be one of <code>FLUSH</code> or <code>TERMINATE</code>
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[CronPumpOptions]]
== CronPumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[cron]]`cron`|`String`|
+++
Quartz cron expression
 <p>
 The official documentation to write your own epression is available at
 <a href="http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html">this address</a>.
+++
|[[data]]`data`|`Json object`|
+++
The custom data to add with the tick
 <p>
 It can be any arbitrary json/yaml data.
 <p>
 No additional data is sent when it is null or empty
+++
|[[emitter]]`emitter`|`String`|
+++
The emitter class
 Provides the ability to execute custom job by providing a custom implementation of a <code>CronEmitter</code>
 <p>
 This can be useful to extract a dataset for batch process on a bunch of single items.
 <p>
 Defaults to <code>fr.myprysm.pipeline.pump.CronEmitter</code>
+++
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|===

[[DataExtractorProcessorOptions]]
== DataExtractorProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[extract]]`extract`|`Json object`|
+++
The list of fields to extract from input json.
 <p>
 If one of the fields is not found in the input object, the field is ignored.
 <p>
 As key, the path to extract a value from input event.
 As value, the path to put this value to the output event.
 <p>
 The complete event can be referenced with the keywork <code>$event</code>
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[DeploymentVerticleOptions]]
== DeploymentVerticleOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[jmxEnabled]]`jmxEnabled`|`Boolean`|-
|[[metrics]]`metrics`|`Boolean`|-
|===

[[EventBusPumpOptions]]
== EventBusPumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
The address to listen on the event bus.
 <p>
 The pump can only listen to one topic.
+++
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|===

[[EventBusSinkOptions]]
== EventBusSinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[publish]]`publish`|`Array of String`|
+++
Publication addresses.
 <p>
 Those publications are broadcasted to each registered consumer.
+++
|[[send]]`send`|`Array of String`|
+++
Publication addresses.
 <p>
 Those publications are casted to the first registered consumer that get the message.
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[ExchangeOptions]]
== ExchangeOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[controlChannel]]`controlChannel`|`String`|
+++
The control channel to emit/receive signals.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The channel cannot be configured</b>
+++
|[[from]]`from`|`String`|
+++
The address the deployed object will receive items from.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The address cannot be configured</b>
+++
|[[to]]`to`|`Array of String`|
+++
The addresses the deployed object will send results to.
 <p>
 This is automatically configured when the pipeline is built.
 <b>The address cannot be configured</b>
+++
|===

[[FileSinkOptions]]
== FileSinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchSize]]`batchSize`|`Number (Integer)`|
+++
The batch size of the link.
 <p>
 It must be a positive link.
 <p>
 It defaults to <code>10</code>
+++
|[[file]]`file`|`String`|
+++
The file name without extension.
 <p>
 Path and file will be tested on startup to detect whether the link can write.
 <p>
 Defaults to <code>output</code>
+++
|[[format]]`format`|`link:enums.html#Format[Format]`|
+++
The format output of the link.
 <p>
 <code>JSON</code> and <code>YAML</code> are supported.
+++
|[[mode]]`mode`|`link:enums.html#Mode[Mode]`|
+++
The mode of the link
+++
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[path]]`path`|`String`|
+++
The path to store the output.
 <p>
 Path and file will be tested on startup to detect whether the link can write.
 <p>
 Defaults to <code>/tmp</code>
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[FlushableSinkOptions]]
== FlushableSinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[batchSize]]`batchSize`|`Number (Integer)`|
+++
The batch size of the link.
 <p>
 It must be a positive link.
 <p>
 It defaults to <code>10</code>
+++
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[ForkProcessorOptions]]
== ForkProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[publish]]`publish`|`Array of String`|
+++
Publication addresses.
 <p>
 Those publications are broadcasted to each registered consumer.
+++
|[[send]]`send`|`Array of String`|
+++
Publication addresses.
 <p>
 Those publications are casted to the first registered consumer that get the message.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[HttpGetRequestProcessorOptions]]
== HttpGetRequestProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[headers]]`headers`|`Json object`|
+++
The headers to send with the request
 <p>
 This is a map of strings that will be automatically added as request headers on each request the processor will send.
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
 <p>
 This can be used to provide some authentication token.
+++
|[[host]]`host`|`String`|
+++
The remote host
+++
|[[injection]]`injection`|`String`|
+++
The field to inject the response into
 <p>
 Once request is made it seems quite obvious that if the request responds data you will somehow use it.
 By using <code>injection</code> you will be able to write response data into this field in the current event.
 <p>
 If you don't need the response, you can use the keyword <code>none</code>, the response data will be automatically discarded.
 <p>
 Defaults to <code>response</code>
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[onError]]`onError`|`link:enums.html#OnError[OnError]`|
+++
Behaviour on error.
 <p>
 Can be one of:
 <ul>
 <li>CONTINUE</li>
 <li>DISCARD</li>
 </ul>
+++
|[[pathParams]]`pathParams`|`Json object`|
+++
The path parameters
 <p>
 Parameters will be put in place of matching placeholders in the url.
 <p>
 Example :
 <p>
 URL: <code>/resource/:foo/route/:bar/values</code>
 <p>
 Path parameters: <pre>
 pathParams:
   foo: $event.foo.id
   bar: with
 </pre>
 <p>
 Called url will be: <code>/some/parameters/route/with/values</code>
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types.
+++
|[[port]]`port`|`Number (Integer)`|
+++
The connection port to remote
 <p>
 If port is set to default, then it will automatically switch from port <code>80</code> to port <code>443</code>
 when <code>HTTPS</code> is enabled.
+++
|[[protocol]]`protocol`|`link:enums.html#Protocol[Protocol]`|
+++
The protocol to use
 <p>
 Can be either <code>HTTP</code> or <code>HTTPS</code>.
 If no port is provided, then it will automatically switch from port <code>80</code> to port <code>443</code>.
+++
|[[queryParams]]`queryParams`|`Json object`|
+++
The query parameters
 <p>
 Parameters will be added as <code>paramKey=paramValue</code> to the url.
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
+++
|[[responseType]]`responseType`|`link:enums.html#ResponseType[ResponseType]`|
+++
The response type
 <p>
 Used for response deserialization, can be one of:
 <ul>
 <li><code>LIST</code></li>
 <li><code>OBJECT</code></li>
 <li><code>LONG</code></li>
 <li><code>DOUBLE</code></li>
 <li><code>STRING</code></li>
 </ul>
 <p>
 Defaults to <code>OBJECT</code>.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|[[url]]`url`|`String`|
+++
The remote url
 <p>
 Used in combination with host, will represent the <code>absolute URI</code> to the remote server.
 <p>
 This url can contain path parameters that will be replaced automatically with  values extracted from the current event.
 Path parameters are url fragments beginning with <code>:</code> (column).
 <p>
 URL examples :
 <ul>
 <li><code>/some/url</code></li>
 <li><code>/some/:parameter/url</code></li>
 <li><code>/</code></li>
 </ul>
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
+++
|[[userAgent]]`userAgent`|`String`|
+++
The user agent to request
 <p>
 Sets an arbitrary user agent to request the remote URL.
 <p>
 Defaults to <code>vertx-pipeline/1.0</code>
+++
|===

[[JoltProcessorOptions]]
== JoltProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[format]]`format`|`link:enums.html#Format[Format]`|
+++
The format of the JOLT specs file.
 <p>
 Either <code>json</code> or <code>yaml</code>
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[path]]`path`|`String`|
+++
The path to a JOLT specs file.
 <p>
 The file can be either <code>JSON</code> or <code>YAML</code>.
 It must be a list of JOLT transforms. Documentation can be found on their <a href="http://bazaarvoice.github.io/jolt/">website</a>.
 <p>
 <b>This option is exclusive with <code>specs</code> option. If a file is set and valid, file specs will overwrite <code>specs</code>.</b>
+++
|[[specs]]`specs`|`Json array`|
+++
The JOLT specs as a list of transforms.
 <p>
 Please check JOLT documentation on their <a href="http://bazaarvoice.github.io/jolt/">website</a>.
 <p>
 <b>This option is exclusive with <code>path</code> option. If a file is set and valid, <code>specs</code> will be overwritten.</b>
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[LogProcessorOptions]]
== LogProcessorOptions

++++
 Log Processor options.
 <p>
 They extend directly base link and provide
 the ability to set the acceptable level to log incoming messages.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[level]]`level`|`link:enums.html#Level[Level]`|
+++
The log  to write the incoming items.
 <p>
 Defaults to <code>DEBUG</code>.
 <p>
 One of:
 <ul>
 <li><code>TRACE</code></li>
 <li><code>DEBUG</code></li>
 <li><code>INFO</code></li>
 <li><code>WARN</code></li>
 <li><code>ERROR</code></li>
 </ul>
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[MergeBasicProcessorOptions]]
== MergeBasicProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[defaultCapacity]]`defaultCapacity`|`Number (Long)`|
+++
The default capacity of the accumulated map, configured on startup.
 <p>
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[onFlush]]`onFlush`|`Json object`|
+++
The list of operations to apply on the accumulated map.
 <p>
 Operations available:
 <ul>
 <li>sort: sorts the objects based on the value at path. Default is ASC</li>
 </ul>
 If the operation is not one of those allowed, it is ignored.
+++
|[[operations]]`operations`|`Json object`|
+++
The list of operations to apply on the accumulating map.
 <p>
 Operations available:
 <ul>
 <li>objToKey: put the object in the map with the value at path as identifier</li>
 <li>mergeArrays: merges the arrays at given path on cached object</li>
 <li>sortArray: sorts the array at field in the corresponding order. Default is ASC</li>
 </ul>
 <p>
 objToKey is required.
 <p>
 If the operation is not one of those allowed, it is ignored.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[ObjectToArrayProcessorOptions]]
== ObjectToArrayProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[fields]]`fields`|`Json array`|
+++
The list of fields to transform as an array / list.
 <p>
 If one of the fields is not found in the input object, the field is created with an empty array.
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[ProcessorOptions]]
== ProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|===

[[PumpOptions]]
== PumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|===

[[SinkOptions]]
== SinkOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`name`|`String`|
+++
The name of the sink.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your sink for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the sink.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as sink.
+++
|===

[[TimerEmitterProcessorOptions]]
== TimerEmitterProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[delayTerminate]]`delayTerminate`|`Number (Long)`|
+++
The delay before sending <code>TERMINATE</code> signal.
 <p>
 A <code>FLUSH</code> signal is always emitted before sending
 <code>TERMINATE</code> thus setting delay between both emissions
 can help the pipeline finish his job properly, especially when accumulating data.
+++
|[[instances]]`instances`|`Number (Integer)`|
+++
The number of instances to deploy.
 <p>
 Must be a positive link.
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the pump.
 <p>
 The value must be a positive integer.
 <p>
 The pump will emit a message every tick containing the
 current counter and timestamp.
+++
|[[name]]`name`|`String`|
+++
The name of the processor.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your processor for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[signal]]`signal`|`link:enums.html#Signal[Signal]`|
+++
The signal to emit every interval.
 <p>
 Can be one of <code>FLUSH</code> or <code>TERMINATE</code>
+++
|[[type]]`type`|`String`|
+++
The type of the processor.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as processor.
+++
|[[unit]]`unit`|`link:enums.html#TimeUnit[TimeUnit]`|
+++
The time unit of the pump.
 <p>
 The value is one of
+++
|===

[[TimerPumpOptions]]
== TimerPumpOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[data]]`data`|`Json object`|
+++
The custom data to add with the tick
 <p>
 It can be any arbitrary json/yaml data.
 <p>
 No additional data is sent when it is null or empty
+++
|[[interval]]`interval`|`Number (Long)`|
+++
The interval of the pump.
 <p>
 The value must be a positive integer.
 <p>
 The pump will emit a message every tick containing the
 current counter and timestamp.
+++
|[[name]]`name`|`String`|
+++
The name of the pump.
 <p>
 This is automatically populated when the pipeline configuration is a list.
 <p>
 You still can name your pump for any purpose by using a map instead of a list
 when you describe your pipeline.
+++
|[[type]]`type`|`String`|
+++
The type of the pump.
 <p>
 This is the fully qualified name of the <code>class</code> that acts as pump.
+++
|[[unit]]`unit`|`link:enums.html#TimeUnit[TimeUnit]`|
+++
The time unit of the pump.
 <p>
 The value is one of
+++
|===

