= Cheatsheets

[[HttpGetRequestProcessorOptions]]
== HttpGetRequestProcessorOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[headers]]`headers`|`Json object`|
+++
The headers to send with the request
 <p>
 This is a map of strings that will be automatically added as request headers on each request the processor will send.
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
 <p>
 This can be used to provide some authentication token.
+++
|[[host]]`host`|`String`|
+++
The remote host
+++
|[[injection]]`injection`|`String`|
+++
The field to inject the response into
 <p>
 Once request is made it seems quite obvious that if the request responds data you will somehow use it.
 By using <code>injection</code> you will be able to write response data into this field in the current event.
 <p>
 If you don't need the response, you can use the keyword <code>none</code>, the response data will be automatically discarded.
 <p>
 Defaults to <code>response</code>
+++
|[[instances]]`instances`|`Number (Integer)`|-
|[[name]]`name`|`String`|-
|[[onError]]`onError`|`link:enums.html#OnError[OnError]`|
+++
Behaviour on error.
 <p>
 Can be one of:
 <ul>
 <li>CONTINUE</li>
 <li>DISCARD</li>
 </ul>
+++
|[[pathParams]]`pathParams`|`Json object`|
+++
The path parameters
 <p>
 Parameters will be put in place of matching placeholders in the url.
 <p>
 Example :
 <p>
 URL: <code>/resource/:foo/route/:bar/values</code>
 <p>
 Path parameters: <pre>
 pathParams:
   foo: $event.foo.id
   bar: with
 </pre>
 <p>
 Called url will be: <code>/some/parameters/route/with/values</code>
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types.
+++
|[[port]]`port`|`Number (Integer)`|
+++
The connection port to remote
 <p>
 If port is set to default, then it will automatically switch from port <code>80</code> to port <code>443</code>
 when <code>HTTPS</code> is enabled.
+++
|[[protocol]]`protocol`|`link:enums.html#Protocol[Protocol]`|
+++
The protocol to use
 <p>
 Can be either <code>HTTP</code> or <code>HTTPS</code>.
 If no port is provided, then it will automatically switch from port <code>80</code> to port <code>443</code>.
+++
|[[queryParams]]`queryParams`|`Json object`|
+++
The query parameters
 <p>
 Parameters will be added as <code>(?|&amp;)paramKey=paramValue</code> to the url.
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
+++
|[[responseType]]`responseType`|`link:enums.html#ResponseType[ResponseType]`|
+++
The response type
 <p>
 Used for response deserialization, can be one of:
 <ul>
 <li><code>LIST</code></li>
 <li><code>OBJECT</code></li>
 <li><code>LONG</code></li>
 <li><code>DOUBLE</code></li>
 <li><code>STRING</code></li>
 </ul>
 <p>
 Defaults to <code>OBJECT</code>.
+++
|[[type]]`type`|`String`|-
|[[url]]`url`|`String`|
+++
The remote url
 <p>
 Used in combination with host, will represent the <code>absolute URI</code> to the remote server.
 <p>
 This url can contain path parameters that will be replaced automatically with  values extracted from the current event.
 Path parameters are url fragments beginning with <code>:</code> (column).
 <p>
 URL examples :
 <ul>
 <li><code>/some/url</code></li>
 <li><code>/some/:parameter/url</code></li>
 <li><code>/</code></li>
 </ul>
 <p>
 To use data from current event, start the path to your value with <code>$event</code> (e.g. <code>$event.path.to.the.field</code>)
 <p>
 Allowed data are only primitive types and their respective lists.
+++
|[[userAgent]]`userAgent`|`String`|
+++
The user agent to request
 <p>
 Sets an arbitrary user agent to request the remote URL.
 <p>
 Defaults to <code>vertx-pipeline/1.0</code>
+++
|===

